### ISSUE TITLE
Org mode support

### ISSUE THREAD

**Issue by vmiheer** [PaulKinlan/logseq-webpage-title#17]
I might be completely wrong but reading the description (and closed issues)  looks like plugin doesn't support same feature for org-mode file in logseq. It would be great to have the feature for org files too. :)
BTW thank you for the extension.

**Comment by PaulKinlan** [comment]
Thank @vmiheer - I actually have never used org-mode so I'll need to do some research.

**Comment by vmiheer** [comment]
I can provide quick differences org links are: `[[http://example.com][Url to example.com]]`. https://orgmode.org/guide/Hyperlinks.html
If you have any question about syntax I can try to help you :).

**Comment by PaulKinlan** [comment]
Ah cool.

**Comment by PaulKinlan** [comment]
I've just made an update in 1.2.2 where I've landed Org-mode support. Would love a quick test given that I don't use that model.

**Comment by miheerv-cerebras** [comment]
This is awesome, I'll try out and reopen the issue in case something breaks. Again, thank you so much!

**Comment by vmiheer** [comment]
Works flawlessly, thank you!

**Comment by PaulKinlan** [comment]
Brilliant. Let me know if there is anything else that pops up.
