### ISSUE TITLE
Not founding in context menu

### ISSUE THREAD

**Issue by YU000jp** [PaulKinlan/logseq-webpage-title#31]
I found this plugin and would like to use it. I can't find "Get Link Titles" in the context menu.

Worked in v1.2.4 but not in v1.3.0
https://github.com/PaulKinlan/logseq-webpage-title/compare/v1.2.4...v1.3.0#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aL148-R261

**Comment by PaulKinlan** [comment]
Hmm - ok. I'll have a look.
