### ISSUE TITLE
Remove leading and trailing spaces from title

### ISSUE THREAD

**Issue by ubuntudroid** [PaulKinlan/logseq-webpage-title#5]
Some URLs return titles with leading and/or trailing spaces which confuse the markdown parser.

Example URL: https://android-developers.googleblog.com/2022/04/first-preview-privacy-sandbox-android.html

A solution would be to simply trim the title.

**Comment by PaulKinlan** [comment]
```
 [
Android Developers Blog: The first developer preview of Privacy Sandbox on Android
](https://android-developers.googleblog.com/2022/04/first-preview-privacy-sandbox-android.html)
```

For my reference.

**Comment by PaulKinlan** [comment]
This was a good catch. I'll investigate

**Comment by ubuntudroid** [comment]
Neat, works perfectly fine now - thanks for the quick fix! 🤗
