### ISSUE TITLE
Use previous instead of next URL

### ISSUE THREAD

**Issue by ubuntudroid** [PaulKinlan/logseq-webpage-title#6]
My usual flow for entering URLs in logseq is:

1. Copy URL
2. Create a new block in logseq
3. Maybe write a short description or a task
4. Paste URL
5. Maybe add a tag or page reference

If I want the URL to expand to show its title I would always have to move my cursor to before the URL again (as obviously, after pasting the URL my cursor is at the end of the URL). I honestly can't envision any case where the cursor naturally ends up to be before the URL when pasting URLs.

So my question is: why is the next URL taken instead of the previous one? I'm very sure there is a rationale behind it, but I'm just too stupid to see it. 😅 

Regardless I'd still ask for at least a second slash command which converts the previous URL if there is no technical reason to not do so.

**Comment by PaulKinlan** [comment]
That's a good point - I tend to think of my slash commands as `/command ARG` so that's how I mentally think about it, but there are a couple of other options

`/title-all` - converts all the urls in a block.
`/title-previous` - maybe... Anyway I need to think about that.

**Comment by PaulKinlan** [comment]
Just mulling on this further - I might check to see what's to the right and if nothing then to the left.

**Comment by PaulKinlan** [comment]
One final update, I remember why I did this a bit more as well, I wanted the closest URL to the command so that it wouldn't re-encode an encoded URL so I picked the right most URL.... I need to have a bit of a think about how to fix this more broadly

**Comment by PaulKinlan** [comment]
@ubuntudroid I have a question. If you had two URL's in a block and you did `/title` would you expect it to do all of them, one of them?

**Comment by ubuntudroid** [comment]
Good question! I personally would expect just the previous one to be converted, but tbh it is very rare for me to put more than one URL into a block as my blocks tend to be rather atomic.

Converting just one would certainly be more flexible than all of them. Probably another case for having multiple commands.
